apiVersion: v1
kind: Secret
metadata:
  name: user-api-secret
type: Opaque
stringData:
  # Logging Settings
  Logging__LogLevel__Default": Information
  Logging__LogLevel__Microsoft.Hosting.Lifetime: Information

  # Jwt Settings
  JwtSettings__EncriptKey: q8vJc0RrYx3l0m2Y0pV-09jbwqergERWGrgtrTT!!@$i2q8vJc0RrYx3l0m2Y0pV+
  JwtSettings__Audience": CloudGameAudience
  JwtSettings__Issuer": CloudGameApi
  JwtSettings__ExpiresInMinutes: 60  

  # Database connection string
  ConnectionStrings__ConnectionStrings: Server=sqlserver,1433;Database=CloudGameUser;User Id=phSvicero;Password=CloudGame#2026;TrustServerCertificate=True

  # RabbitMQ Settings
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: 5672
  RabbitMq__Username: guest
  RabbitMq__Password: guest

  # Default User data
  AppDefaultUserAdmin__Email: admin@cloudgame.com
  AppDefaultUserAdmin__Password: $argon2id$v=19$m=65536,t=3,p=1$8p6W85A9MT/UQo9zExtjew$2ppLR/7osayS4fMiZWZpzefUdgNhCUyVIVFrBRtOCy0
  AppDefaultUserAdmin__Name: Admin

  # Serilog
  Serilog:
    Using:
      - Serilog.Sinks.Console
      - Serilog.Sinks.File
    MinimumLevel:
      Default: Information
      Override:
        Microsoft: Warning
        System: Warning
    WriteTo:
      - Name: Console
  
      - Name: File
        Args:
          path: Logs/log-.txt
          rollingInterval: Day
          retainedFileCountLimit: 30
          outputTemplate: "[{Timestamp:yyyy-MM-dd HH:mm:ss} {Level:u3}] {SourceContext} - {Message:lj}{NewLine}{Exception}"
  
    Enrich:
      - FromLogContext
      - WithMachineName
      - WithThreadId