services:
  cloudgame.api:
    image: ${DOCKER_REGISTRY-}cloudgameapi
    container_name: cloudgameapi
    build:
      context: .
      dockerfile: CloudGame.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__Default=Server=cloudgame-sqlserver,1433;Database=CloudGameUsersDB;User Id=sa;Password=CloudGame#2026;TrustServerCertificate=True;
      - RabbitMQ__Host=cloudgame-rabbitmq
      - RabbitMQ__Username=admin
      - RabbitMQ__Password=admin123
    ports:
      - '7037:8080'
      - '7038:8081'
    restart: unless-stopped    
    networks:
      - cloudgame-network  
  
networks:
  cloudgame-network:
    external: true
    name: cloudgame-network  