services:
  cloudgame.api:
    image: ${DOCKER_REGISTRY-}cloudgameapi
    container_name: cloudgameapi
    build:
      context: .
      dockerfile: CloudGame.API/Dockerfile
    ports:
      - '7037:8080'
    environment:
      - DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false
      - ASPNETCORE_URLS=http://+:8080   # <- força só HTTP, remove o bind HTTPS
    restart: unless-stopped
    networks:
      - cloudgame-network

networks:
  cloudgame-network:
    external: true